version: "3"

services:
  server:
    container_name: server
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
